# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 40570e61738b966117cbfa86ec696fc33d792e8ed763463318a47267fdb74655675e0a5c8702ad1146ae19b21a8adbffa5f4349a81a24288e2f910cc0bd3d472

test:
  secret_key_base: 1b40a6b8c3f1a0bff3c46af9dba5cc47390a06b18f4838ba1504aa77bd086fe06ce422dd0a91032ee8f1493a019ed8c78338fc7f44ad8d96b7d496d80aa8248f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
